### ISSUE TITLE
Compilation error in file lib/cloud_watch/input_log_event.ex 

### ISSUE THREAD

**Issue by dimun** [heyoutline/cloud_watch#13]
I'm trying to run mix phx.digest in my app and it throws the following error.
`
== Compilation error in file lib/cloud_watch/input_log_event.ex ==
** (ArgumentError) Poison.Encoder is not available
    (elixir) lib/protocol.ex:69: Protocol.assert_protocol!/2
    lib/cloud_watch/input_log_event.ex:4: (module)
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
could not compile dependency :cloud_watch, "mix compile" failed. You can recompile this dependency with "mix deps.compile cloud_watch", update it with "mix deps.update cloud_watch" or clean it with "mix deps.clean cloud_watch"
`

It seems that there is not a dependency for poison in the cloudwatch project, I'm currently using Jason, there is an option for selecting another JSON encoder?

**Comment by pmenhart** [comment]
I assume that you are using the `ExAws` library?
Unfortunately, `input_log_event.ex` depends on Poison.Encoder. This was OK when the CloudWatch project used only the `AWS` Elixir library, which depends on Poison anyway. 

It should be possible to make implementation of `CloudWatch.InputLogEvent` conditional (similar to conditional choice of Aws library in `CloudWatch.AwsProxy`):
 if `Code.ensure_loaded?(Jason)` then call Jason, otherwise use Poison. 
In this way, selection of JSON encoder is left outside of the project.
Please feel free to submit a PR.

**Comment by hashim-sohail** [comment]
@dimun Were you able to fix this?

**Comment by kuiro5** [comment]
👋 Hey @dimun @hashim-sohail

This issue should be fixed in @pmenhart's PR #19 as part of v0.4.0. Once you're able to upgrade, feel free to reopen if you're still having issues.
